name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: source

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.10'

    - name: Build the HTML
      run: ./build.sh

    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Copy book to main branch
      run: |
        cp -r book/* .

    - name: Commit and push to main branch
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'githubaction@users.noreply.github.com'
        git add -A
        git commit -m "Update from GitHub Action"
        git push origin main